package com.tht.ifdatamigrator;

import java.util.List;

import static java.util.List.of;

public final class Const {
    private Const() {
    }

    public static final List<String> VERSIONS = of(
            "MES",
            "MIT-54M5V2",
            "MIT-CAN45V2MT",
            "MIT-CAN45V2",
            "MIT-HC63V3",
            "MIT-RIMA54V2",
            "MIT-54M5RV2",
            "MIT-54M5SV2",
            "MIT-54M5HV2",
            "MIT-54M5MV2",
            "MIT-54M5TV2",
            "MIT-54M5NFV2"
    );

    public static final List<String> COMPANY_NAME_LIST = of(
            "Cambrian Homecare",
            "Crystal Finishing Systems, Inc.",
            "Berrett Pest Control Arizona, Inc. dba Blue Sky Pest Control",
            "Buzzi Unicem USA Inc.",
            "P & S Construction Co., Inc. / PASCON, LLC",
            "Thornapple Manor",
            "Varra Companies Inc",
            "Vita-Herb Nutriceuticals, Inc.",
            "Down to Earth Compliance",
            "Elite Lighting Corp.",
            "K&K Electric, Inc.",
            "Linn Gear Company",
            "RAPAD Drilling & Well Service, Inc.",
            "Richdale Management, Inc.",
            "Telling Industries, LLC",
            "Warehouse Specialists, Inc.",
            "Waste Eliminator, Inc.",
            "Bruns Construction Enterprises Inc",
            "Charter Schools of San Diego",
            "Down River Cleaning Srvc., Inc",
            "Dunmire Development Corporation dba Pueblo Wood Pr",
            "Gary Amoth Trucking Inc",
            "HJ Russell & Company",
            "Interwest Safety Supply, LLC",
            "Lee Drywall Inc",
            "Little Valley Wholesale Nursery",
            "Midwest Capital Holdings Inc",
            "Professional Home Health Care Inc.",
            "Trans United Inc",
            "Wheaton Group, Inc. dba Visiting Angels",
            "Ziker Cleaners Inc",
            "CDI - Aiken Pest Control Inc",
            "CDI - Allgood Services Inc",
            "CDI - Bug Busters USA",
            "CDI - Capital Tower & Communications, Inc.",
            "CDI - CEMTEK Environmental, Inc.",
            "CDI - Coast Packing Company",
            "CDI - Cycle Construction Company, LLC",
            "CDI - Danville Public Building Commission",
            "CDI - Electronic Source Company",
            "CDI - Environmental Transportation of Nevada",
            "CDI - Essential Cabinetry Group",
            "CDI - F.J. Kerrigan Plumbing Company, Inc.",
            "CDI - Joseph L. Blakan, Inc.",
            "CDI - Lutheran Social Ministries of New Jersey, Inc.",
            "CDI - Malouf Construction, LLC",
            "CDI - McLean County 911 Communications Center",
            "CDI - Merit Contracting, Inc.",
            "CDI - PMI Iowa, LLC",
            "CDI - Rose Pest Solutions - BioServe",
            "CDI - Tri-Dim Filter Corporation",
            "CDI - Ventura Pest Control Inc",
            "CDI - Village of Chatham",
            "CDI - Village of South Holland",
            "CDI (IPMG) - Clinton County Sheriff's Office",
            "CDI (IPMG) - Kendall County Emergency Phone Service and Communication Board",
            "CDI (IPMG) - Kendall County Sheriff's Office",
            "CDI (IPMG) - Oak Park Township",
            "CDI (IPMG) - Village of Forest Park",
            "CDI (IPMG) - Village of Oakwood Hills",
            "CDI (IPMG) - Village of Riverwoods",
            "Apex Transportation Inc",
            "Applied Aerospace Structures Corp.",
            "Aspen Painting, Inc.",
            "AWI Management Corporation",
            "Barr Brands International, Inc.",
            "Bay Area Transportation Authority",
            "BG Products, Incorporated",
            "Bixler Corporation",
            "Brister-Stephens, Inc.",
            "ChemDesign Products, Inc.",
            "Clemson Distribution, Inc.",
            "Daniels Tire Service",
            "Donley Service Center, Inc.",
            "Dove Pointe, Inc.",
            "Heritage Landscape Services, Inc.",
            "Heritage Provider Network, Inc.",
            "Highwoods Contracting Corporation",
            "HNM Systems",
            "International Aerospace Coatings, Inc.",
            "International Risk Management Institute, Inc.",
            "Mega Rentals, Inc.",
            "Montana Lines",
            "New Leaf Landscape Services, Inc.",
            "NOW Health Group, Inc.",
            "Prime Plumbing Incorporated",
            "Social Model Recovery Systems, Inc.",
            "The WaterLeaf at Land Park",
            "Tipton Asset Group, Inc.",
            "Town of Carbondale",
            "Velocity Constructors, Inc.",
            "Village Management Services, Inc.",
            "York Imperial Plastics, Inc.",
            "O'Hara Corporation",
            "Smith Senior Living",
            "Smart Care Equipment Solutions (EEC Acquisition, LLC)",
            "International Marine and Industrial Applicators, I",
            "Carmelite Sisters of the Devine Heart, of Missouri",
            "Wright & McGill Co",
            "Kaluzny Bros. Inc.",
            "Penn Beer Distributors, Inc.",
            "Atlanta Bonded Warehouse Corporation",
            "Behrens and Associates, Inc.",
            "Kenpat USA LLC",
            "Singletrack Electric LLC",
            "D. Armstrong Contracting, LLC",
            "Restoneovation, LLC",
            "Sequoia Beverage, Company, LP",
            "Bill's Tool Rental, Inc.",
            "Midwest Transit Equipment, Inc.",
            "Oak Ridge Winery, LLC",
            "Hawaii Tire Co., LLC",
            "Unity Works Lighting LLC",
            "Matthews Studio Equipment, Inc.",
            "Central Phoenix Eye Care",
            "Rex Heat Treat - Lansdale, Inc.",
            "Frank Motors, Inc.",
            "North American Roofing Services, Inc.",
            "Alan's Lawn and Garden Center, Inc.",
            "Murray & Stafford Inc",
            "F.B. Harding, Inc.",
            "FIRST Services Corp of Orlando",
            "Southwest Aquatics (Desert Limnologists, Inc.)",
            "CDI - Rottler Pest and Lawn Solutions",
            "CDI - Premier Magnesia, LLC",
            "CDI - Baker Rock Resources",
            "CDI - Earth Island",
            "CDI - City of Macomb, Illinois",
            "CDI - Bloomingdale Fire Protection District",
            "CDI - CPI Acquisitions, LLC",
            "CDI - American Paper & Twine Company",
            "CDI - Banks Construction Company",
            "CDI - Pestcom Pest Management LLC",
            "CDI - City of Momence",
            "CDI - Oregon Mainline Paving, LLC",
            "CDI - Palos Fire Protection District",
            "CDI - City of Mattoon Police Department",
            "CDI - Insurance Program Managers Group",
            "CDI (IPMG) - City of Carlyle",
            "CDI (IPMG) - Barrington Police Department",
            "Heath Village",
            "Overeasy, Inc.",
            "Elite Manufacturing & Professional Services, Inc.",
            "Summit Consulting Services, Inc.",
            "The Maids International",
            "Bret's Electric, LLC"
    );

    public static final List<String> COMPANY_NUMS = of(
            "0743",
            "1906",
            "2148",
            "1541",
            "1886",
            "1702",
            "1973",
            "2082",
            "2146",
            "1649",
            "1148",
            "1630",
            "1749",
            "1581",
            "1610",
            "1635",
            "1798",
            "0043",
            "1238",
            "2145",
            "1325",
            "1613",
            "2002",
            "2046",
            "1291",
            "1874",
            "1592",
            "0722",
            "1540",
            "1406",
            "1662",
            "2141",
            "2147",
            "1770",
            "0370",
            "1985",
            "1480",
            "0902",
            "2067",
            "2098",
            "1937",
            "2099",
            "2036",
            "1901",
            "2031",
            "2137",
            "1912",
            "2125",
            "2138",
            "2037",
            "0855",
            "1099",
            "1292",
            "1242",
            "1678",
            "1240",
            "1182",
            "2050",
            "3370",
            "1815",
            "2096",
            "1915",
            "0961",
            "1735",
            "1338",
            "0283",
            "0162",
            "1515",
            "1387",
            "1498",
            "2055",
            "1297",
            "1310",
            "2010",
            "1176",
            "1795",
            "2083",
            "2054",
            "1421",
            "1427",
            "1425",
            "1760",
            "1600",
            "1949",
            "1880",
            "1830",
            "1619",
            "1465",
            "2030",
            "1860",
            "2060",
            "2029",
            "1884",
            "1820",
            "2095",
            "1966",
            "1078",
            "1730",
            "1766",
            "1889",
            "1557",
            "2034",
            "2149",
            "0875",
            "2078",
            "1117",
            "2015",
            "2097",
            "1681",
            "2115",
            "0783",
            "1437",
            "1256",
            "2047",
            "1466",
            "2142",
            "1970",
            "1955",
            "2139",
            "1950",
            "2085",
            "1356",
            "1984",
            "1433",
            "1618",
            "1796",
            "1892",
            "1897",
            "1918",
            "1945",
            "1958",
            "1979",
            "2026",
            "2048",
            "2074",
            "2075",
            "2121",
            "2122",
            "2132",
            "2134",
            "2016",
            "1861",
            "1896",
            "1792",
            "0336",
            "2025"
    );
}
